name: Build Pipeline

# Events that trigger the workflow
on:
  # Trigger the workflow on push events to the main branch
  push:
    branches:
      - '*' # Push events to all branches
  # Also trigger the workflow on pull request events to the integration branch
  pull_request:
    branches:
      - integration
jobs:
  build_pipeline:
    runs-on: ubuntu-latest
    env:
      MONGODB_URI: ${{ secrets.MONGODB_URI }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.8.0'

      - name: Install dependencies
        run: npm install

      - name: Run Front End Unit Tests
        run: npm test

      - name: Build
        run: |
          npm run build
  
  Automated-API-Tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
    
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.8.0'

      - name: Install dependencies
        run: npm install

      - name: Run application in development mode
        run: npm run dev

      - name: Install Postman CLI
        run: |
          curl -o- "https://dl-cli.pstmn.io/install/linux64.sh" | sh

      - name: Login to Postman CLI
        run: postman login --with-api-key ${{ secrets.POSTMAN_API_KEY }}

      - name: Run API tests
        run: |
          postman collection run "30462678-cafdc9db-fd86-461f-aff5-0289751d64d8" -e "30462678-7e209f10-f09a-482e-bdbd-99752db5d6ff"





